name=input("Enter your name:") 
sem=int(input("Enter your semester:")) 
city=input("Enter your city name:") 
pincode=int(input("Enter a pincode of your city:"))
college=input("Enter your college")
mobile=int(input("enter your mobile number:"))
print("Student Name :",name) 
print("Semester:",sem) 
print("City:",city) 
print("Pincode:",pincode) 
print("Collge:",college)
print("Mobile:",mobile)
